### ISSUE TITLE
Bugs around cards blanking each other

### ISSUE THREAD

**Issue by KingSupernova31** [jpraet/fantasy-realms#3]
There seem to be a number of (probably-related) bugs when there are more than 2 cards blanking each other or themselves. Examples:

* Blizzard, Rainstorm, Wildfire, and Book of Changes (turning Blizzard into a Flood). Blizzard should be blanking itself.
* Blizzard, Great Flood, Wildfire, and Book of Changes (turning Blizzard into a Beast). All cards except Book of Changes should be blanking each other.

**Comment by jpraet** [comment]
Hi, thanks for submitting the bug report.

The first example seems to be working correctly for me?
https://fantasy-realms.github.io/index.html?hand=FR11,FR12,FR16,FR49+FR49:FR12:flood

Your second example of 3 cards cyclically blanking each other does not seem to be working, indeed:
https://fantasy-realms.github.io/index.html?hand=FR12,FR08,FR16,FR49+FR49:FR12:beast

**Comment by KingSupernova31** [comment]
Ah, it looks like the bug is dependent on the order in which the cards are added to the app. If I add Rainstorm first ([link](https://fantasy-realms.github.io/index.html?hand=FR16,FR49,FR11,FR12+FR49:FR12:flood)) then there is no bug, but if I add Blizzard first ([link](https://fantasy-realms.github.io/index.html?hand=FR16,FR49,FR12,FR11+FR49:FR12:flood)) then the bug happens.

**Comment by jpraet** [comment]
I reworked the blanking logic in the app. These 2 issues are fixed now. I hope I didn't break anything else with these changes.
You may need to clear your cache to get the updated version.

If you encounter any more bugs, please report them here instead: https://github.com/fantasy-realms/fantasy-realms.github.io/issues
